nfo:
  component: Edge Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /services
  routes:
    address: 
      path: /address/**
      serviceId: address-service
    customer: 
      path: /employee/**
      serviceId: employee-service  
    consumer:
      path: /producer/**
      serviceId : producer-service
              

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false
      
server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG